apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  size: 1x.extra-small
  storage:
    schemas:
    - version: v12
      effectiveDate: "2023-04-01"
    secret:
      name: loki-s3-secret
      type: s3
  storageClassName: thin-csi
  tenants:
    mode: openshift-logging